-- Curated Dream Symbol Library
-- Generated: 2026-02-07T03:43:20.905Z
-- Total symbols: 45

-- First, clear existing curated symbols
DELETE FROM symbols WHERE source = 'curated';

-- Insert curated symbols
INSERT INTO symbols (name, meaning, shadow, guidance, category, keywords, related_symbols, source) VALUES
  ('Water', 'Emotions, the unconscious mind, purification, and the flow of life. Water''s state reflects emotional states - calm water suggests peace, turbulent water indicates emotional turmoil.', 'Overwhelming emotions, fear of drowning in feelings, emotional repression', 'What emotions are you currently navigating? Are you going with the flow or fighting against the current?', 'Nature', ARRAY['emotion', 'feelings', 'unconscious', 'flow', 'cleansing'], ARRAY['Ocean', 'River', 'Rain', 'Flood'], 'curated'),
  ('Ocean', 'The vast unconscious, collective emotions, the unknown depths of the psyche. Represents both infinite possibility and the mysteries we haven''t explored.', 'Fear of the unknown, feeling lost in overwhelming emotions, isolation', 'What undiscovered territories of your inner life are calling to be explored?', 'Nature', ARRAY['depth', 'vastness', 'unconscious', 'mystery', 'emotion'], ARRAY['Water', 'Waves', 'Beach', 'Fish'], 'curated'),
  ('Fire', 'Transformation, passion, destruction and renewal, anger, enlightenment. Fire consumes the old to make way for the new.', 'Destructive anger, burnout, consuming passions that harm', 'What in your life needs to be transformed? What passion needs healthy expression?', 'Nature', ARRAY['transformation', 'passion', 'anger', 'destruction', 'renewal'], ARRAY['Sun', 'Candle', 'Smoke', 'Ash'], 'curated'),
  ('Forest', 'The unconscious mind, getting lost in thought, discovery, the unknown path. Forests represent the wild, untamed aspects of the psyche.', 'Feeling lost, fear of the unknown, being unable to see the way forward', 'What undiscovered parts of yourself are waiting to be found in the wilderness of your mind?', 'Nature', ARRAY['unconscious', 'lost', 'discovery', 'nature', 'wild'], ARRAY['Trees', 'Path', 'Animals', 'Darkness'], 'curated'),
  ('Mountain', 'Obstacles, achievements, spiritual ascent, higher perspective. Mountains represent challenges that lead to growth and expanded views.', 'Insurmountable challenges, isolation at the top, exhaustion from climbing', 'What summit are you working toward? Is the climb worth the view?', 'Nature', ARRAY['challenge', 'achievement', 'perspective', 'obstacle', 'height'], ARRAY['Climbing', 'Peak', 'Valley', 'Snow'], 'curated'),
  ('Sun', 'Consciousness, vitality, clarity, masculine energy, success. The sun illuminates truth and brings warmth to cold situations.', 'Harsh scrutiny, overexposure, ego inflation, burnout', 'What needs to be brought into the light? Where do you need more warmth and vitality?', 'Nature', ARRAY['consciousness', 'clarity', 'energy', 'success', 'light'], ARRAY['Light', 'Day', 'Fire', 'Gold'], 'curated'),
  ('Moon', 'Intuition, the feminine, cycles, the unconscious, dreams within dreams. The moon reflects hidden emotions and inner knowing.', 'Illusion, deception, lunacy, being ruled by emotions', 'What does your intuition whisper when you quiet your mind? What cycle are you in?', 'Nature', ARRAY['intuition', 'feminine', 'cycles', 'unconscious', 'reflection'], ARRAY['Night', 'Stars', 'Tides', 'Silver'], 'curated'),
  ('Rain', 'Cleansing, renewal, sadness, fertility, release of emotions. Rain washes away the old and nourishes new growth.', 'Depression, feeling drowned by circumstances, gloom that won''t lift', 'What needs to be washed away? What seeds are being nourished by this difficult season?', 'Nature', ARRAY['cleansing', 'tears', 'renewal', 'sadness', 'growth'], ARRAY['Water', 'Storm', 'Clouds', 'Umbrella'], 'curated'),
  ('Storm', 'Emotional upheaval, conflict, powerful change, clearing the air. Storms represent the release of built-up tension.', 'Destructive emotions, chaos, feeling out of control', 'What tension has been building that needs release? How can you find shelter while the storm passes?', 'Nature', ARRAY['conflict', 'change', 'chaos', 'release', 'power'], ARRAY['Lightning', 'Thunder', 'Rain', 'Wind'], 'curated'),
  ('River', 'The flow of life, time passing, journey, emotional currents. Rivers carry us forward whether we resist or surrender.', 'Being swept away, unable to change direction, stagnation when blocked', 'Are you flowing with life or fighting against its current?', 'Nature', ARRAY['flow', 'journey', 'time', 'movement', 'current'], ARRAY['Water', 'Bridge', 'Boat', 'Fish'], 'curated'),
  ('Snake', 'Transformation, healing, hidden fears, wisdom, kundalini energy. Snakes shed their skin, representing renewal and change.', 'Betrayal, hidden threats, toxic situations or people, sexual fears', 'What old skin are you ready to shed? What healing transformation awaits?', 'Animals', ARRAY['transformation', 'healing', 'fear', 'wisdom', 'renewal'], ARRAY['Venom', 'Shedding', 'Garden', 'Reptile'], 'curated'),
  ('Dog', 'Loyalty, friendship, protection, unconditional love, instincts. Dogs represent our faithful companions and our own loyal nature.', 'Aggression, feeling attacked, loyalty to the wrong things, domestication', 'Who or what deserves your loyalty? Are you being true to yourself?', 'Animals', ARRAY['loyalty', 'friendship', 'protection', 'instinct', 'companion'], ARRAY['Wolf', 'Pet', 'Pack', 'Guard'], 'curated'),
  ('Cat', 'Independence, intuition, feminine power, mystery, sensuality. Cats move between worlds and see in the dark.', 'Aloofness, selfishness, bad luck superstitions, hidden aggression', 'Where do you need more independence? What does your intuition tell you?', 'Animals', ARRAY['independence', 'intuition', 'mystery', 'feminine', 'grace'], ARRAY['Tiger', 'Lion', 'Night', 'Eyes'], 'curated'),
  ('Bird', 'Freedom, perspective, the soul, messages, transcendence. Birds rise above earthly concerns and see the bigger picture.', 'Flightiness, being scattered, inability to stay grounded', 'What higher perspective do you need? What message is trying to reach you?', 'Animals', ARRAY['freedom', 'flight', 'soul', 'message', 'perspective'], ARRAY['Wings', 'Feathers', 'Sky', 'Nest'], 'curated'),
  ('Horse', 'Power, freedom, nobility, passion, drive. Horses represent the vital force that carries us forward in life.', 'Unbridled passions, loss of control, being ridden by others'' demands', 'What is driving you forward? Are you in control of your own power?', 'Animals', ARRAY['power', 'freedom', 'drive', 'nobility', 'energy'], ARRAY['Rider', 'Saddle', 'Running', 'Wild'], 'curated'),
  ('Spider', 'Creativity, patience, fate, the web of life, feminine power. Spiders weave intricate webs connecting all things.', 'Feeling trapped, manipulation, fear of the feminine, being caught', 'What are you weaving in your life? Are you the spider or caught in someone''s web?', 'Animals', ARRAY['creativity', 'patience', 'fate', 'web', 'weaving'], ARRAY['Web', 'Insect', 'Trap', 'Thread'], 'curated'),
  ('Wolf', 'Instincts, intelligence, freedom, social connections, the wild self. Wolves balance independence with pack loyalty.', 'Predatory behavior, isolation from the pack, being hunted', 'How do you balance your wild nature with your social bonds?', 'Animals', ARRAY['instinct', 'wild', 'pack', 'hunter', 'loyalty'], ARRAY['Dog', 'Moon', 'Forest', 'Howl'], 'curated'),
  ('Fish', 'The unconscious, fertility, Christianity, abundance, emotions swimming beneath the surface.', 'Slippery situations, cold emotions, being out of your element', 'What swims beneath the surface of your awareness?', 'Animals', ARRAY['unconscious', 'fertility', 'abundance', 'depth', 'swimming'], ARRAY['Water', 'Ocean', 'Fishing', 'Scale'], 'curated'),
  ('Bear', 'Strength, introspection, the mother, hibernation and renewal, standing your ground.', 'Aggression, overbearing behavior, withdrawing too much', 'What requires your strength? Is it time to retreat and restore?', 'Animals', ARRAY['strength', 'mother', 'hibernation', 'power', 'protection'], ARRAY['Cave', 'Forest', 'Cubs', 'Honey'], 'curated'),
  ('House', 'The self, the psyche, different rooms represent different aspects of personality. Your inner home and sense of self.', 'Neglected parts of self, hidden rooms, structural instability in identity', 'Which rooms of your inner house need attention? What have you been avoiding?', 'Places', ARRAY['self', 'psyche', 'home', 'rooms', 'shelter'], ARRAY['Room', 'Door', 'Attic', 'Basement'], 'curated'),
  ('School', 'Learning life lessons, feeling tested, personal growth, past experiences that shaped you.', 'Anxiety about performance, feeling judged, unfinished business from the past', 'What lesson is life teaching you now? What old patterns need to be unlearned?', 'Places', ARRAY['learning', 'lesson', 'test', 'growth', 'past'], ARRAY['Teacher', 'Test', 'Classroom', 'Books'], 'curated'),
  ('Hospital', 'Healing, need for care, health concerns, emotional wounds being tended.', 'Fear of illness, feeling broken, being unable to heal yourself', 'What part of you needs healing? Are you allowing yourself to receive care?', 'Places', ARRAY['healing', 'health', 'care', 'wound', 'recovery'], ARRAY['Doctor', 'Medicine', 'Bed', 'Surgery'], 'curated'),
  ('Church', 'Spirituality, seeking meaning, moral questions, community, the sacred within.', 'Guilt, judgment, rigid beliefs, spiritual bypassing', 'What do you hold sacred? How do you connect with something greater than yourself?', 'Places', ARRAY['spirituality', 'sacred', 'religion', 'meaning', 'community'], ARRAY['Prayer', 'Altar', 'Priest', 'Ceremony'], 'curated'),
  ('Road', 'Life path, journey, direction in life, choices about which way to go.', 'Being lost, dead ends, dangerous paths, going in circles', 'What path are you on? Is it time to choose a new direction?', 'Places', ARRAY['path', 'journey', 'direction', 'choice', 'travel'], ARRAY['Car', 'Walking', 'Crossroads', 'Map'], 'curated'),
  ('Door', 'Opportunity, transition, new beginnings, access to hidden parts of self.', 'Closed opportunities, secrets, fear of what lies beyond', 'What doors are opening or closing in your life? Which ones are you afraid to open?', 'Objects', ARRAY['opportunity', 'transition', 'opening', 'threshold', 'choice'], ARRAY['Key', 'House', 'Lock', 'Entrance'], 'curated'),
  ('Key', 'Solutions, access, secrets revealed, power to unlock, knowledge.', 'Locked out, missing piece, secrets that should stay hidden', 'What do you hold the key to? What remains locked away?', 'Objects', ARRAY['solution', 'access', 'secret', 'unlock', 'power'], ARRAY['Door', 'Lock', 'Treasure', 'Mystery'], 'curated'),
  ('Mirror', 'Self-reflection, truth, vanity, seeing yourself clearly, the soul.', 'Distorted self-image, being unable to face yourself, illusions', 'What do you see when you truly look at yourself? What are you avoiding?', 'Objects', ARRAY['reflection', 'truth', 'self', 'image', 'identity'], ARRAY['Face', 'Glass', 'Double', 'Vanity'], 'curated'),
  ('Car', 'Control over life direction, how you move through the world, personal drive and ambition.', 'Loss of control, accidents, being driven by someone else', 'Are you in the driver''s seat of your life? Where are you heading?', 'Objects', ARRAY['control', 'direction', 'drive', 'journey', 'movement'], ARRAY['Road', 'Driver', 'Crash', 'Speed'], 'curated'),
  ('Phone', 'Communication, connection, messages trying to reach you, intuition calling.', 'Missed connections, inability to communicate, being unreachable', 'Who or what is trying to reach you? What message are you not receiving?', 'Objects', ARRAY['communication', 'connection', 'message', 'call', 'contact'], ARRAY['Voice', 'Number', 'Ring', 'Text'], 'curated'),
  ('Money', 'Self-worth, power, resources, energy exchange, values.', 'Greed, poverty consciousness, measuring worth by wealth', 'What do you truly value? How do you measure your own worth?', 'Objects', ARRAY['worth', 'value', 'power', 'resources', 'exchange'], ARRAY['Gold', 'Wallet', 'Bank', 'Coins'], 'curated'),
  ('Book', 'Knowledge, life story, wisdom, learning, the record of your experiences.', 'Living by the book, closed chapters you can''t access, information overload', 'What chapter of your life are you writing now? What wisdom do you seek?', 'Objects', ARRAY['knowledge', 'story', 'wisdom', 'learning', 'chapter'], ARRAY['Library', 'Pages', 'Writing', 'Reading'], 'curated'),
  ('Clothes', 'Identity, how you present yourself, roles you play, persona.', 'False identity, being exposed, wearing masks', 'Who are you when no one is watching? Are you wearing the right clothes for this chapter?', 'Objects', ARRAY['identity', 'persona', 'appearance', 'role', 'covering'], ARRAY['Naked', 'Dress', 'Shoes', 'Uniform'], 'curated'),
  ('Flying', 'Freedom, transcendence, rising above problems, spiritual elevation, ambition achieved.', 'Escaping reality, fear of falling, being untethered from ground', 'What do you need to rise above? Are you flying toward something or away from something?', 'Actions', ARRAY['freedom', 'transcendence', 'elevation', 'escape', 'soaring'], ARRAY['Bird', 'Wings', 'Sky', 'Falling'], 'curated'),
  ('Falling', 'Loss of control, anxiety, letting go, failure fears, surrender.', 'Feeling unsupported, actual danger, inability to trust', 'What are you afraid of losing? Can you trust the fall?', 'Actions', ARRAY['control', 'anxiety', 'surrender', 'fear', 'release'], ARRAY['Flying', 'Cliff', 'Depth', 'Ground'], 'curated'),
  ('Being Chased', 'Avoidance, running from problems, anxiety, something requiring attention.', 'Paranoia, actual threats, exhaustion from running', 'What are you running from? What would happen if you turned to face it?', 'Actions', ARRAY['avoidance', 'fear', 'pursuit', 'escape', 'anxiety'], ARRAY['Running', 'Monster', 'Shadow', 'Escape'], 'curated'),
  ('Teeth Falling Out', 'Anxiety about appearance, communication issues, loss of power, transition.', 'Aging fears, loss of control, inability to express yourself', 'What are you afraid to say? What power do you feel you''re losing?', 'Actions', ARRAY['anxiety', 'appearance', 'communication', 'power', 'loss'], ARRAY['Mouth', 'Speaking', 'Eating', 'Smile'], 'curated'),
  ('Being Naked', 'Vulnerability, authenticity, fear of exposure, nothing to hide, freedom from pretense.', 'Shame, feeling judged, inappropriate exposure', 'Where in your life do you feel exposed? Can you embrace your vulnerability?', 'Actions', ARRAY['vulnerability', 'exposure', 'shame', 'authenticity', 'truth'], ARRAY['Clothes', 'Public', 'Body', 'Hiding'], 'curated'),
  ('Death', 'Endings, transformation, major life changes, letting go of the old self.', 'Fear of change, grief, resistance to necessary endings', 'What part of your life or self is ready to die so something new can be born?', 'Actions', ARRAY['ending', 'transformation', 'change', 'rebirth', 'letting go'], ARRAY['Funeral', 'Grave', 'Ghost', 'Rebirth'], 'curated'),
  ('Pregnancy', 'New beginnings, creativity, projects gestating, potential, nurturing something new.', 'Unwanted responsibilities, fear of what you''re creating, long wait', 'What are you birthing into the world? What needs more time to develop?', 'Actions', ARRAY['creation', 'potential', 'development', 'nurturing', 'birth'], ARRAY['Baby', 'Birth', 'Mother', 'Growth'], 'curated'),
  ('Baby', 'New beginnings, innocence, vulnerability, your inner child, fresh starts.', 'Helplessness, neediness, neglected parts of self', 'What new beginning needs your nurturing? How is your inner child?', 'Actions', ARRAY['innocence', 'new', 'vulnerable', 'potential', 'nurture'], ARRAY['Pregnancy', 'Child', 'Mother', 'Birth'], 'curated'),
  ('Mother', 'Nurturing, the feminine, unconditional love, origin, protection, the Great Mother archetype.', 'Smothering, abandonment issues, the devouring mother', 'How do you nurture yourself and others? What is your relationship with the feminine?', 'People', ARRAY['nurturing', 'feminine', 'love', 'origin', 'protection'], ARRAY['Baby', 'Home', 'Earth', 'Womb'], 'curated'),
  ('Father', 'Authority, protection, the masculine, structure, guidance, the Great Father archetype.', 'Tyranny, absent father, judgment, rigid control', 'What is your relationship with authority and structure? How do you express the masculine?', 'People', ARRAY['authority', 'masculine', 'protection', 'guidance', 'structure'], ARRAY['King', 'Boss', 'Sky', 'Law'], 'curated'),
  ('Child', 'Innocence, playfulness, your younger self, new beginnings, spontaneity.', 'Immaturity, neglected inner child, childish behavior', 'What does your inner child need? Where do you need more play?', 'People', ARRAY['innocence', 'play', 'youth', 'spontaneous', 'wonder'], ARRAY['Baby', 'Toy', 'School', 'Game'], 'curated'),
  ('Stranger', 'Unknown aspects of self, the shadow, new possibilities, the unfamiliar.', 'Fear of the unknown, projection, danger from outside', 'What unknown part of yourself is this stranger representing?', 'People', ARRAY['unknown', 'shadow', 'mystery', 'other', 'unfamiliar'], ARRAY['Shadow', 'Face', 'Crowd', 'Meeting'], 'curated'),
  ('Shadow Figure', 'The rejected self, repressed qualities, what you deny, the Jungian shadow.', 'Integration needed, dangerous denial, confrontation with self', 'What qualities have you rejected that this shadow embodies?', 'People', ARRAY['shadow', 'repressed', 'denied', 'dark', 'unconscious'], ARRAY['Dark', 'Stranger', 'Monster', 'Chase'], 'curated')
ON CONFLICT (name) DO UPDATE SET
  meaning = EXCLUDED.meaning,
  shadow = EXCLUDED.shadow,
  guidance = EXCLUDED.guidance,
  category = EXCLUDED.category,
  keywords = EXCLUDED.keywords,
  related_symbols = EXCLUDED.related_symbols,
  source = EXCLUDED.source;
